### ISSUE TITLE
Add support for experimental field agency.txt agency_email

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-application-modules#152]
We're working on improving the feedback process from OneBusAway users back to the agencies (see https://github.com/OneBusAway/onebusaway-android/pull/392 for details), and several OBA agencies (HART, Sound Transit, ARC) have expressed an interest in allowing users to communicate with the agency customer service department via email.  

Agency email address would be a per-agency field (vs. per region), so the GTFS data is the most logical place to maintain it.  GTFS [`agency.txt`](https://developers.google.com/transit/gtfs/reference#agencytxt) currently contains an `agency_phone` and `agency_url`, so it seems logical to add this email address in a new field `agency_email`.

HART in Tampa, FL will add `agency.txt agency_email` to their production GTFS starting Nov. 1st.  A preview GTFS dataset we can use to test `agency_email` support in this application is [here](https://dl.dropboxusercontent.com/u/46443835/OneBusAway/hart_agency_email/google_transit.zip).

Sound Transit has also tentatively agreed to add this field, although we don't have a release date yet.

ARC in Atlanta is talking with MARTA, the local transit agency, to see if they are interested in adding this field.

Related issue - https://github.com/OneBusAway/onebusaway-gtfs-modules/issues/61.

cc @cagryInside

**Comment by cagryInside** [comment]
HART included `agency_fare_url` to GTFS data. @barbeau Do we want to add `agency_fare_url` to this implementation?

```
agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_fare_url,agency_email
Hillsborough Area Regional Transit,http://www.gohart.org,America/New_York,en,813-254-4278,http://gohart.storesecured.com,gohart.service@gmail.com

```

**Comment by barbeau** [comment]
@cagryInside Good catch!  Yes, `agency_fare_url` is part of the official spec as an optional field:
https://developers.google.com/transit/gtfs/reference#agencytxt

...so please go ahead and add it.  We can find a way to include this in OBA mobile apps too.

**Comment by cagryInside** [comment]
Just pushed two commits for `onebusaway-application-modules` and `onebusaway-gtfs-modules`.

Commit for `onebusaway-application-modules`: https://github.com/cagryInside/onebusaway-application-modules/commit/d99a5255fcd10e5669dcc0bb33e126dc15fb482e

Commit for  `onebusaway-gtfs-modules`: https://github.com/cagryInside/onebusaway-gtfs-modules/commit/b873f9cfe401f19dea35b6cca461ad1d19be4cb3

Now we are showing `email` and `fareUrl` fields.

```

agencies: [
{
id: "Hillsborough Area Regional Transit",
privateService: false,
phone: "813-254-4278",
timezone: "America/New_York",
disclaimer: "",
email: "gohart.service@gmail.com",
name: "Hillsborough Area Regional Transit",
fareUrl: "http://gohart.storesecured.com",
lang: "en",
url: "http://www.gohart.org"
}
]
```

cc @barbeau

**Comment by barbeau** [comment]
@cagryInside Awesome!  Looks good to me - are there any tests that cover the existing agency fields?  If so, please go ahead and add these new fields to the tests.  If not, please go ahead and open PRs against both projects.

**Comment by cagryInside** [comment]
@barbeau There is one issue that I would like to discuss with you tomorrow. Current `onebusaway-application-modules` uses  `onebusaway-gtfs-modules`  with version 1.2.6. However, the latest `onebusaway-gtfs-modules` project version is 1.3.5. So, I have made the changes on top of the old version. We might wanna change the `onebusaway-application-modules` in order to work with the latest version.

**Comment by barbeau** [comment]
@cagryInside Sounds good, let's discuss tomorrow.  I think I remember seeing that at some point also.

**Comment by barbeau** [comment]
@sheldonabrown We have these new fields implemented (commits [here](https://github.com/cagryInside/onebusaway-application-modules/commit/d99a5255fcd10e5669dcc0bb33e126dc15fb482e) and [here](https://github.com/cagryInside/onebusaway-gtfs-modules/commit/b873f9cfe401f19dea35b6cca461ad1d19be4cb3)) and would like to get them into OBA Tampa soon.  However, we're hitting an issue when trying to use the master branch of `oba-gtfs-modules` (`v1.3.5-SNAPSHOT`) with the develop/master branch of `oba-app-modules`.

We get this stack trace when trying to build the bundle:

~~~
Exception in thread "main" java.lang.NoClassDefFoundError: org/onebusaway/csv_entities/HasExtensions
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethods(Unknown Source)
	at org.springframework.core.type.StandardAnnotationMetadata.hasAnnotatedMethods(StandardAnnotationMetadata.java:136)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.checkConfigurationClassCandidate(ConfigurationClassBeanDefinitionReader.java:320)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:172)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:142)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:599)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:407)
	at org.onebusaway.container.ContainerLibrary.createContext(ContainerLibrary.java:108)
	at org.onebusaway.transit_data_federation.bundle.FederatedTransitDataBundleCreator.run(FederatedTransitDataBundleCreator.java:173)
	at org.onebusaway.transit_data_federation.bundle.FederatedTransitDataBundleCreatorMain.run(FederatedTransitDataBundleCreatorMain.java:218)
	at org.onebusaway.transit_data_federation.bundle.FederatedTransitDataBundleCreatorMain.main(FederatedTransitDataBundleCreatorMain.java:91)
Caused by: java.lang.ClassNotFoundException: org.onebusaway.csv_entities.HasExtensions
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
~~~

`oba-app-modules` is currently using `v1.2.6` of `oba-gtfs-modules`.  If we apply our same changes to that version of `oba-gtfs-modules` and use it with `oba-app-modules`, everything works fine and we see the new fields in the API response.

Any ideas to get `oba-app-modules` working with newest version of `oba-gtfs-modules`?  And where should we be submitting the PRs for `onebusaway-gtfs-modules` and `onebusaway-application-modules` to get this feature into OBA Tampa?

**Comment by sheldonabrown** [comment]
Let me take a look -- I'll verify the dependencies are consistent.

We've done a bunch of work here:
https://github.com/camsys/onebusaway-application-modules/tree/unified

(and I believe we've already updated the gtfs modules there as well)

We are hoping to slowly merge this back to
onebusaway/onebusaway-application-modules, but in the meantime where you've
committed is fine, I'll merge from there.

**Comment by barbeau** [comment]
@sheldonabrown Awesome, thanks!  Please give me a heads up when it goes live - at that point I'll open a thread on gtfs-changes to see if we can get the `agency_email` field officially added to GTFS.

BTW, MARTA is Atlanta is now including `agency_email` as well:
http://www.itsmarta.com/google_transit_feed/google_transit.zip

cc @landonreed, as he'll want to update the ARC OBA instance with these fields as well.

@landonreed see above discussion - we have commits adding this field to OBA, although there are some issues getting it into the main OBA project at the moment.

**Comment by barbeau** [comment]
I've written an official proposal to add `agency_email` to the GTFS spec here:
https://groups.google.com/forum/#!topic/gtfs-changes/aezjQsriLYA

**Comment by barbeau** [comment]
`agency_email` was officially added to GTFS on Feb 3rd:
https://groups.google.com/d/msg/gtfs-changes/aezjQsriLYA/PKJ1zpqbBAAJ
