### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by israteneda** [OneBusAway/onebusaway-application-modules#228]
I followed OneBusAway Quickstart Guide for testing OneBusAway. The app runs correctly with the command:
```
java -jar onebusaway-quickstart-assembly-1.1.16-api-webapp.war -webapp /opt/bundle/
```
but when I try to run in a test server with the nohup command:

```
nohup java -jar onebusaway-quickstart-assembly-1.1.16-api-webapp.war -webapp /opt/bundle/ &
```

The app shows the next error:

```
=============================================================
=
= Your OneBusAway instance has started.  Browse to:
=
= http://localhost:8080/
=
= to see your instance in action.
=
= When you are finished, press return to exit gracefully...
=============================================================
java.io.IOException: Bad file descriptor
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at org.onebusaway.quickstart.bootstrap.WebappBootstrapMain.run(WebappBootstrapMain.java:134)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.onebusaway.quickstart.bootstrap.BootstrapMain$1.run(BootstrapMain.java:199)
        at java.lang.Thread.run(Thread.java:748)
```
Thank you for your help.

**Comment by israteneda** [comment]
I could not directly run the war file in the background with nohup command, so I followed the [Configuration and Deployment Guide for v1.x](https://github.com/OneBusAway/onebusaway/wiki/Configuration-and-Deployment-Guide-for-v1.x) and I am running the quick start application with Tomcat server.

**Comment by aaronbrethorst** [comment]
Quickstart is deprecated. please see our Docker project instead: https://github.com/OneBusAway/docker
