### ISSUE TITLE
OBA v.2.x.x running tomcat8 don't have permission for log files

### ISSUE THREAD

**Issue by jSantiago318** [OneBusAway/onebusaway-application-modules#276]
Joshua RSI
unread,
2:50 PM (now) 
to onebusaway-developers
Hello: 
I have been following the Configuration and Development Guide for OBA v2. Ive created the OBA bundle with my gtfs and  followed the instructions as such. The only difference is that I am running Debian 10 on Windows (wsl). After configuring the specified files and running the tomcat8. The following errors shows: 

```
04-Nov-2020 14:54:12.127 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /var/log/tomcat6/tds.2020-11-04.log (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
        at org.apache.log4j.rolling.RollingFileAppender.activateOptions(RollingFileAppender.java:179)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:295)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
        at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:492)
        at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1001)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:867)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:773)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:66)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:156)
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:301)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4701)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1859)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
04-Nov-2020 14:54:12.436 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
04-Nov-2020 14:54:12.437 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/onebusaway-transit-data-federation-webapp] startup failed due to previous errors
04-Nov-2020 14:54:12.459 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/var/lib/tomcat8/webapps/onebusaway-transit-data-federation-webapp] has finished in [1,633] ms
04-Nov-2020 14:54:12.461 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
04-Nov-2020 14:54:12.471 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 6790 ms


```

Additionaly all of the services show a 404 error. Tomcat8 is running yet no page is found only the default tomcat localhost:8080

Previously I was trying to build a OBA v1.1.19. But due to a depricated class when creating the webapp I was suggested to change to the latest OBA (v.2.x.x). Any help or suggestion on a common error or a OBA version preference is greatly appreciated.

Thank You in advance

**Comment by jSantiago318** [comment]
to onebusaway-developers
If this is of any help:

When OBA was runing on tomcat8 it didn't have permission to change or create files on the log directory. After running the following line on terminal the tomcat8 ran without the errors. Altough I still have a 404 error on every page the log error is gone.

`  sudo chown -R tomcat8:tomcat8 /var/log/tomcat8/  `

**Comment by sheldonabrown** [comment]
Thanks Joshua,

in the log4j.xml in each webapp, you'll need to change the
`/var/log/tomcat6` to some appropriate path on your system, or soft-link
/var/log/tomcat6 to some other path on your system.

It is a quirk, I appreciate that, but it is what it is.

Sheldon
