### ISSUE TITLE
Error building bundles v2.0.0

### ISSUE THREAD

**Issue by brodyFlannigan** [OneBusAway/onebusaway-application-modules#345]
Hi!

I'm attempting to build a bundle using the v2.0.0 precompiled transit-data-federation-builder JARfile from the Nexus repo and am getting this error: 

```java
2023-06-17 20:34:26,725 ERROR [FederatedTransitDataBundleCreatorMain.java:211] : error building transit data bundle
java.lang.IllegalStateException: error invoking refresh method=public void org.onebusaway.transit_data_federation.impl.ExtendedCalendarServiceImpl.start() on target object=org.onebusaway.transit_data_federation.impl.ExtendedCalendarServiceImpl@1752e45c
        at org.onebusaway.container.refresh.RefreshServiceImpl.invokePair(RefreshServiceImpl.java:134)
        at org.onebusaway.container.refresh.RefreshServiceImpl.refresh(RefreshServiceImpl.java:45)
        at org.onebusaway.transit_data_federation.bundle.tasks.CalendarServiceDataTask.run(CalendarServiceDataTask.java:90)
        at org.onebusaway.transit_data_federation.bundle.FederatedTransitDataBundleCreator.run(FederatedTransitDataBundleCreator.java:202)
        at org.onebusaway.transit_data_federation.bundle.FederatedTransitDataBundleCreatorMain.run(FederatedTransitDataBundleCreatorMain.java:209)
        at org.onebusaway.transit_data_federation.bundle.FederatedTransitDataBundleCreatorMain.main(FederatedTransitDataBundleCreatorMain.java:88)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.onebusaway.container.refresh.RefreshServiceImpl.invokePair(RefreshServiceImpl.java:132)
        ... 5 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.onebusaway.transit_data_federation.model.transit_graph.TransitGraph.getAllBlocks()" because "this._graph" is null
        at org.onebusaway.transit_data_federation.impl.transit_graph.TransitGraphDaoImpl.getAllBlocks(TransitGraphDaoImpl.java:121)
        at org.onebusaway.transit_data_federation.impl.ExtendedCalendarServiceImpl.determineAllServiceIds(ExtendedCalendarServiceImpl.java:442)
        at org.onebusaway.transit_data_federation.impl.ExtendedCalendarServiceImpl.cacheServiceDatesForServiceIds(ExtendedCalendarServiceImpl.java:415)
        at org.onebusaway.transit_data_federation.impl.ExtendedCalendarServiceImpl.start(ExtendedCalendarServiceImpl.java:96)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 7 more
``` 

I'm using [VIA Rail's GTFS](https://www.viarail.ca/sites/all/files/gtfs/viarail.zip) but am also getting this error with the [STO's data](http://www.contenu.sto.ca/GTFS/GTFS.zip).

Would someone be able to look into this to see what's going on?

**Comment by aaronbrethorst** [comment]
I don't know about v2.0.0, but with the latest bits, `v2.4.18-cs` in the [Dockerized bundler](https://github.com/onebusaway/onebusaway-docker), both GTFS feeds are working for me.

Although I should add that parsing the feed from STO does throw up some different, non-fatal errors:

```
oba_bundler-1  | 00:35:46.331 [pool-6-thread-4] ERROR org.onebusaway.transit_data_federation.impl.transit_graph.DistanceAlongShapeLibrary - We were attempting to compute the distance along a particular trip for each stop time of that trip by snapping them to the shape for that trip.  However, we found WAY TOO MANY potential assignments, which usually indicates that there is something wrong with the underlying shape data.  For more information on errors of this kind, see:
oba_bundler-1  |   https://github.com/OneBusAway/onebusaway-application-modules/wiki/Stop-to-Shape-Matching
```
